version: "3"

services:
    R1R3-django:
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        container_name: R1R3-django
        # depends_on:
        #     - R1R3-potgresql
        environment:
            TZ: Asia/Shanghai
        ports:
            - 8000:8000
        expose:
            - 8000
        restart: always
        networks:
            network:
                ipv4_address: 177.8.0.12

    R1R3-web:
        container_name: R1R3-web
        build:
            context: ./
            dockerfile: ./docker/web/Dockerfile
        # depends_on:
        #     - R1R3-django
        ports:
            - 8080:8080
        expose:
            - 8080
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/conf.d/R1R3.conf
        environment:
            TZ: Asia/Shanghai
        networks:
            network:
                ipv4_address: 177.8.0.11

    # R1R3-potgresql:
    #     image: postgresql:10
    #     container_name: R1R3-potgresql
    #     restart: always
    #     ports:
    #         - 54320:5432
    #     expose:
    #         - 5432
    #     environment:
    #         MYSQL_ROOT_PASSWORD: "root"
    #         MYSQL_DATABASE: "R1R3"
    #         TZ: Asia/Shanghai
    #     volumes:
    #         - potgresql:/var/lib/potgresql
    #     networks:
    #         network:
    #             ipv4_address: 177.8.0.13

volumes:
    mysql:
    redis:

networks:
    network:
        ipam:
            driver: default
            config:
                - subnet: '177.8.0.0/16'
